import tkinter as tk
from tkinter import *
import random
import time
from tkinter import ttk
from tkinter import Button
import tkinter.messagebox

class App(tk.Frame):
    def __init__(self, master):
        tk.Frame.__init__(self, master)
        self.pack()
        self.master.title("Quoridor Online")
        self.master.configure(background="black")
        tk.Label (self, text="**Quoridor**", bg="black", fg="white", font="none 20 bold").pack(fill='x')
        tk.Label (self, text="________________________________________________________", bg="black", fg="white", font="none 20 bold").pack()
        canvas = Canvas(master, width=500, height=500)
        canvas.pack()
        def cColor(e,B3):
                e.widget.configure(bg = "red")
        #First row of grid
        topFrame=Frame(canvas)
        topFrame.pack()
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')

        def cColor(e):
            e.widget.configure(bg = "red")
        
        #first row of walls
        topFrame=Frame(canvas)
        topFrame.pack()
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        
        #First row of grid
        topFrame=Frame(canvas)
        topFrame.pack()
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')

        #first row of walls
        topFrame=Frame(canvas)
        topFrame.pack()
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        
        #First row of grid
        topFrame=Frame(canvas)
        topFrame.pack()
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')

        #first row of walls
        topFrame=Frame(canvas)
        topFrame.pack()
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        
        #First row of grid
        topFrame=Frame(canvas)
        topFrame.pack()
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')

        #first row of walls
        topFrame=Frame(canvas)
        topFrame.pack()
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')

        #First row of grid
        topFrame=Frame(canvas)
        topFrame.pack()
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        
        #first row of walls
        topFrame=Frame(canvas)
        topFrame.pack()
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        
        #First row of grid
        topFrame=Frame(canvas)
        topFrame.pack()
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')    
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')      
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')

        #first row of walls
        topFrame=Frame(canvas)
        topFrame.pack()
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        
        #First row of grid
        topFrame=Frame(canvas)
        topFrame.pack()
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')

       #first row of walls
        topFrame=Frame(canvas)
        topFrame.pack()
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')   
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')

        #First row of grid
        topFrame=Frame(canvas)
        topFrame.pack()
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')

        #first row of walls
        topFrame=Frame(canvas)
        topFrame.pack()
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=1, height=1, bg="gray", fg='gray', command=self.clickwall)
        B1.pack(side='left')
        B1=tk.Button(topFrame,width=5, height=1, bg="lightcyan", fg='gray')
        B1.pack(side='left')

        #First row of grid
        topFrame=Frame(canvas)
        topFrame.pack()
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=1, height=2, bg="lightcyan", fg='gray')
        B2.pack(side='left')
        B2=tk.Button(topFrame,width=5, height=2, bg="lightyellow", fg='gray')
        B2.pack(side='left')

        

    def clickwall(self):
        M=tkinter.messagebox.showinfo("Window Title","If you want a Horizontal wall choose 'YES'")
        M1=tkinter.messagebox.askquestion("","Horizontal wall?")
        if M1=="yes":
                N1=tkinter.messagebox.showinfo("","You put a Horizontal wall in the board")
                self.B2.bind("<Button-1>", cColor)
                    

        if M1=="no":
            N2=tkinter.messagebox.showinfo("","You put a Vertical wall in the board")


        
    
#for move ava in game




        
if __name__=='__main__':
    root = tk.Tk()
    root.geometry()
    app = App(root)
    app.mainloop
